new GameManager and GameStateManager
anjx123/DungeonPartyGameDev pull request #38
Opened 2023-05-20 05:32 UTC by Hanson-Sun

added a new GameManager class

since its unity, the game manager is a singleton unity object that extends MonoBehavior 

GameStateManager is not fully implemented as it has no use currently

2023-05-22 01:42 UTC, leo-cf-tian requested changes
Pretty good, could use a few simplifications though.

2023-05-22 01:42 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameManager.cs
> +        get
consider using a lambda function lol

2023-05-22 01:42 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameManager.cs
> +                GameObject gameManager = new GameObject();
consider using null coalescing operators

2023-05-22 01:42 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameManager.cs
> +        if (instance != null && instance != this)
not something you need to change, but you could do without parentheses probably

2023-05-22 01:42 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameStateManager.cs
> +        get
same comment about lambda functions

2023-05-22 01:42 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameStateManager.cs
> +            instance ??= new GameStateManager();
you use it here lol

2023-05-22 01:43 UTC, Hanson-Sun commented on Assets/Scripts/SceneUtility/GameManager.cs
> +                GameObject gameManager = new GameObject();
he wants the ??

2023-05-22 01:45 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameManager.cs
> +                GameObject gameManager = new GameObject();
yep, you could probably use it with the lambda function too to make it way shorter

2023-05-22 01:46 UTC, Hanson-Sun commented on Assets/Scripts/SceneUtility/GameStateManager.cs
> +            instance ??= new GameStateManager();
* the linter did it

2023-05-22 01:47 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/GameStateManager.cs
> +            instance ??= new GameStateManager();
You should do it to!

2023-05-23 23:32 UTC, anjx123 approved these changes
Manager looks good tbh, its probably good enough for now since we have no use for so much functionality.

2023-05-23 23:53 UTC, leo-cf-tian approved these changes

2023-05-23 23:55 UTC, merged