Al fire perk
anjx123/DungeonPartyGameDev pull request #48
Opened 2023-05-24 16:53 UTC by anjx123

Implemented basic structure for Buffs, and a foundation perk for future perks

2023-05-28 03:39 UTC, leo-cf-tian requested changes

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/BuffScripts/Buff.cs
> +    public float GetDuration()
could we consider a property here?

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/BuffScripts/Resistance.cs
> +
extraneous newline, might as well get rid of it :P

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/PerkScripts/FireResistance/FireResistance.cs
> +    public override void OnStart(Player player)
if it's nothing, you can omit it.

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/PerkScripts/FireResistance/FireResistance.cs
> +    void Start()
you might want to define names etc. at the top for clarity.

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/PerkScripts/Perk.cs
> +
extraneous newlines

2023-05-28 03:39 UTC, leo-cf-tian commented on Assets/Scripts/PerkScripts/Perk.cs
> +    public void SetName(string name)
same thing about setting names

2023-05-28 21:11 UTC, Yikachu commented
wait we didnt merge this??? berm...

2023-05-30 20:40 UTC, leo-cf-tian approved these changes
1 style nit, feel free to merge after changing it

2023-05-30 20:40 UTC, leo-cf-tian commented on Assets/Scripts/PlayerScripts/Player.cs
> +
extraneous newline

2023-05-31 04:04 UTC, merged