Al trap abstraction
anjx123/DungeonPartyGameDev pull request #5
Opened 2023-05-14 19:28 UTC by anjx123

Refactored player script

Refactored existing script names

Added abstract trap class

2023-05-14 20:01 UTC, anjx123 commented on Assets/Scripts/PlayerScripts/PlayerHealth.cs
>          healthBar.SetMaxHealth(MAX_HEALTH);
Resolved, the set max health is necessary to make sure the slider has the correct scaling

2023-05-14 20:02 UTC, anjx123 commented on Assets/Scripts/TrapScripts/TrapTags.cs
> +    [Header("Elemental Type")]
Enemies would always have the floor placement tag automatically attached.

2023-05-14 20:26 UTC, leo-cf-tian requested changes

2023-05-14 20:26 UTC, leo-cf-tian commented on Assets/Scripts/TrapScripts/ProjectileTrap.cs
> +        if (timer <= fireInterval)
Erm... wut. Logical error lol.

2023-05-14 20:26 UTC, leo-cf-tian commented on Assets/Scripts/TrapScripts/ProjectileTrap.cs
> +public abstract class ProjectileTrap : Trap
We could probably just generalize this into the Trap class, up to you though. Some traps that do not shoot projectiles may also have periodic effects.

2023-05-14 20:26 UTC, leo-cf-tian commented on Assets/Scripts/TrapScripts/TrapTags.cs
> +    [Header("Trap Classification")]
We just discussed this... Consider changing maybe.

2023-05-14 20:26 UTC, leo-cf-tian commented on Assets/Scripts/PlayerScripts/PlayerHealth.cs
>              TakeDamage(-100);
Newline here too.

2023-05-14 20:42 UTC, anjx123 commented on Assets/Scripts/TrapScripts/ProjectileTrap.cs
> +public abstract class ProjectileTrap : Trap
I would rather not, the main thing about projectile trap is that it must have a projectile object to instantiate

2023-05-15 02:39 UTC, leo-cf-tian commented on Assets/Scripts/TrapScripts/ProjectileTrap.cs
> +public abstract class ProjectileTrap : Trap
couldn't we just make it a nullable field?

2023-05-15 02:50 UTC, leo-cf-tian approved these changes
Just a few style nits (some were my bad lol)
Also, see my question about projectile traps and nullable fields. Maybe it doesn't work for unity, idk.
After that feel free to merge.

2023-05-15 02:50 UTC, leo-cf-tian commented on Assets/Scripts/PlayerScripts/PlayerHealth.cs
> +
Oomf should have made myself clear, only if there is actual code before the condition and not just at the beginning of the function. My bad.

2023-05-15 02:50 UTC, leo-cf-tian commented on Assets/Scripts/PlayerScripts/PlayerHealth.cs
> +
Since you moved the if statement you can get rid of the newline at the end too

2023-05-15 02:50 UTC, leo-cf-tian commented on Assets/Scripts/PlayerScripts/PlayerMovement.cs
>              Debug.Log("I am Dashing");
Consider getting rid of the debug log, I'm not sure if Leon has already done it.

2023-05-15 03:12 UTC, merged