Update camera follow implementation
anjx123/DungeonPartyGameDev pull request #6
Opened 2023-05-14 20:19 UTC by Hanson-Sun

2023-05-14 20:41 UTC, leo-cf-tian requested changes

2023-05-14 20:41 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +    public float smoothSpeed = 3.5f;
Please make variables const whenever possible. Note that consts should come before all other fields.

2023-05-14 20:41 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +        offset.y = -2f;
Just curious what this is for.

2023-05-14 20:54 UTC, Hanson-Sun commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +        offset.y = -2f;
if its not there it wont work 😰

2023-05-14 21:03 UTC, Hanson-Sun commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +    public float smoothSpeed = 3.5f;
only smoothspeed should be a const

2023-05-14 21:19 UTC, anjx123 commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +    public float smoothSpeed = 3.5f;
If you make the smooth speed public, you can set it in the editor and so you dont have to set it inside the script

2023-05-15 02:32 UTC, leo-cf-tian commented on Assets/Scripts/SceneUtility/CameraFollowPlayer.cs
> +    public float smoothSpeed = 3.5f;
that also works, depends on you implementation.

2023-05-15 02:34 UTC, leo-cf-tian approved these changes

2023-05-15 02:53 UTC, merged